
package com.mindbox.test.pe.webservices.wsimportgen;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PowerEditorAPIInterface", targetNamespace = "http://webservices.server.pe.mindbox.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PowerEditorAPIInterface {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.mindbox.test.pe.webservices.wsimportgen.PowerEditorInterfaceReturnStructure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deploy", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.Deploy")
    @ResponseWrapper(localName = "deployResponse", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.DeployResponse")
    public PowerEditorInterfaceReturnStructure deploy(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<Integer> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        List<Integer> arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        boolean arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        boolean arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        boolean arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        boolean arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        boolean arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        boolean arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        boolean arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        boolean arg16);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.mindbox.test.pe.webservices.wsimportgen.PowerEditorInterfaceReturnStructure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importEntities", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ImportEntities")
    @ResponseWrapper(localName = "importEntitiesResponse", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ImportEntitiesResponse")
    public PowerEditorInterfaceReturnStructure importEntities(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.mindbox.test.pe.webservices.wsimportgen.PowerEditorInterfaceReturnStructure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importEntitiesWithCredentials", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ImportEntitiesWithCredentials")
    @ResponseWrapper(localName = "importEntitiesWithCredentialsResponse", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ImportEntitiesWithCredentialsResponse")
    public PowerEditorInterfaceReturnStructure importEntitiesWithCredentials(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg20
     * @param arg19
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.mindbox.test.pe.webservices.wsimportgen.PowerEditorInterfaceReturnStructure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exportDataWithCredentials", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ExportDataWithCredentials")
    @ResponseWrapper(localName = "exportDataWithCredentialsResponse", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ExportDataWithCredentialsResponse")
    public PowerEditorInterfaceReturnStructure exportDataWithCredentials(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        boolean arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        boolean arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        boolean arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        boolean arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        boolean arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        List<String> arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        List<Integer> arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        List<Integer> arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        boolean arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        int arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        String arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        String arg20);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.mindbox.test.pe.webservices.wsimportgen.PowerEditorInterfaceReturnStructure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exportData", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ExportData")
    @ResponseWrapper(localName = "exportDataResponse", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.ExportDataResponse")
    public PowerEditorInterfaceReturnStructure exportData(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        boolean arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        boolean arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        boolean arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        boolean arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        boolean arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        List<String> arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        List<Integer> arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        List<Integer> arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        boolean arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        int arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.mindbox.test.pe.webservices.wsimportgen.PowerEditorInterfaceReturnStructure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deployWithCredentials", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.DeployWithCredentials")
    @ResponseWrapper(localName = "deployWithCredentialsResponse", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.DeployWithCredentialsResponse")
    public PowerEditorInterfaceReturnStructure deployWithCredentials(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<Integer> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        List<Integer> arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        boolean arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        boolean arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        boolean arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        boolean arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        boolean arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        boolean arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        boolean arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        boolean arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18);

    /**
     * 
     * @return
     *     returns com.mindbox.test.pe.webservices.wsimportgen.PowerEditorInterfaceReturnStructure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://webservices.server.pe.mindbox.com/", className = "com.mindbox.test.pe.webservices.wsimportgen.PingResponse")
    public PowerEditorInterfaceReturnStructure ping();

}
