
ALTER TABLE MB_AUDIT MODIFY EDIT_VALUE_TO VARCHAR(255);

CREATE TABLE MB_MESSAGE (
    MESSAGE_ID INT NOT NULL,
    MESSAGE_TEXT MEMO NOT NULL ,
    CHANNEL_ID INT NOT NULL ,
    ACTIVATION_DATE DATETIME NOT NULL ,
    EXPIRATION_DATE DATETIME NULL,
    PRIMARY KEY (MESSAGE_ID)
);

CREATE TABLE MB_MESSAGE_TEMPLATE (
    MESSAGE_ID INT NOT NULL,
    TEMPLATE_ID INT NOT NULL,
    COLUMN_ID INT NOT NULL,
    PRIMARY KEY (MESSAGE_ID)
);

INSERT INTO MB_PRIVILEGE (PRIVILEGE_ID,PRIVILEGE_NAME,DISPLAY_STRING) VALUES (40,'ManageMessages','Manage Override Messages');
INSERT INTO MB_ROLE_PRIVILEGE (PRIVILEGE_ID,ROLE_ID) VALUES (40,2);
