CREATE TABLE MB_CBR_CASE_CLASS (
	case_class_id INT NOT NULL,
	display_name VARCHAR(32) NOT NULL,
	symbol VARCHAR(32) NOT NULL,
	PRIMARY KEY ( case_class_id )
);

INSERT INTO MB_CBR_CASE_CLASS (case_class_id, symbol, display_name) VALUES (1, 'CBR:AUTOGENERATED_CASE', 'Auto-generated');
INSERT INTO MB_CBR_CASE_CLASS (case_class_id, symbol, display_name) VALUES (2, 'CBR:MANUALLYGENERATED_CASE', 'Manulally Generated');

CREATE TABLE MB_CBR_SCORING_FUNCTION (
	scoring_function_id INT NOT NULL,
	display_name VARCHAR(32) NOT NULL,
	symbol VARCHAR(32) NOT NULL,
	PRIMARY KEY ( scoring_function_id )
);

INSERT INTO MB_CBR_SCORING_FUNCTION (scoring_function_id, symbol, display_name) VALUES (1, 'CBR:SCORE-WITH-PRESENTED-MAX', 'Presented Maximum');
INSERT INTO MB_CBR_SCORING_FUNCTION (scoring_function_id, symbol, display_name) VALUES (2, 'CBR:SCORE-WITH-STORED-MAX', 'Stored Maximum');
INSERT INTO MB_CBR_SCORING_FUNCTION (scoring_function_id, symbol, display_name) VALUES (3, 'CBR:SCORE-WITH-BOTH-MAX', 'Both Maximum');

CREATE TABLE MB_CBR_CASE_ACTION (
	case_action_id INT NOT NULL,
	display_name VARCHAR(32) NOT NULL,
	symbol VARCHAR(32) NOT NULL,
	PRIMARY KEY ( case_action_id )
);

INSERT INTO MB_CBR_CASE_ACTION (case_action_id, symbol, display_name) VALUES (1, 'CBR:WALK', 'Walk');
INSERT INTO MB_CBR_CASE_ACTION (case_action_id, symbol, display_name) VALUES (2, 'CBR:RUN', 'Run');
INSERT INTO MB_CBR_CASE_ACTION (case_action_id, symbol, display_name) VALUES (3, 'CBR:SWIM', 'Swim');
INSERT INTO MB_CBR_CASE_ACTION (case_action_id, symbol, display_name) VALUES (4, 'CBR:BIKE', 'Bike');
INSERT INTO MB_CBR_CASE_ACTION (case_action_id, symbol, display_name) VALUES (5, 'CBR:SKATE', 'Skate');
INSERT INTO MB_CBR_CASE_ACTION (case_action_id, symbol, display_name) VALUES (6, 'CBR:SKI', 'Ski');

CREATE TABLE MB_CBR_ATTRIBUTE_TYPE (
	attribute_type_id INT NOT NULL,
	display_name VARCHAR(32) NOT NULL,
	symbol VARCHAR(32) NOT NULL,
	default_match_contribution INT NOT NULL,
	default_mismatch_penalty INT NOT NULL,
	default_absence_penalty INT NOT NULL,
	default_value_range_id INT NOT NULL,
	ask_for_match_interval INT NOT NULL,
	ask_for_numeric_range INT NOT NULL,
	PRIMARY KEY ( attribute_type_id )
);

INSERT INTO MB_CBR_ATTRIBUTE_TYPE (attribute_type_id, symbol, display_name, default_match_contribution, default_mismatch_penalty,
	default_absence_penalty, default_value_range_id, ask_for_match_interval, ask_for_numeric_range) VALUES
	(1, 'CBR:STRING', 'String', 100, 0, 0, 1, 0, 0);
INSERT INTO MB_CBR_ATTRIBUTE_TYPE (attribute_type_id, symbol, display_name, default_match_contribution, default_mismatch_penalty,
	default_absence_penalty, default_value_range_id, ask_for_match_interval, ask_for_numeric_range) VALUES
	(2, 'CBR:SYMBOL', 'Symbol', 100, 0, 0, 1, 0, 0);
INSERT INTO MB_CBR_ATTRIBUTE_TYPE (attribute_type_id, symbol, display_name, default_match_contribution, default_mismatch_penalty,
	default_absence_penalty, default_value_range_id, ask_for_match_interval, ask_for_numeric_range) VALUES
	(3, 'CBR:WORD', 'Word', 100, 0, 0, 1, 0, 0);
INSERT INTO MB_CBR_ATTRIBUTE_TYPE (attribute_type_id, symbol, display_name, default_match_contribution, default_mismatch_penalty,
	default_absence_penalty, default_value_range_id, ask_for_match_interval, ask_for_numeric_range) VALUES
	(4, 'CBR:DIRECT-WORD', 'Direct Word', 100, 0, 0, 1, 0, 0);
INSERT INTO MB_CBR_ATTRIBUTE_TYPE (attribute_type_id, symbol, display_name, default_match_contribution, default_mismatch_penalty,
	default_absence_penalty, default_value_range_id, ask_for_match_interval, ask_for_numeric_range) VALUES
	(5, 'CBR:FLAT-OBJECT', 'Flat Object', 100, 0, 0, 1, 0, 0);
INSERT INTO MB_CBR_ATTRIBUTE_TYPE (attribute_type_id, symbol, display_name, default_match_contribution, default_mismatch_penalty,
	default_absence_penalty, default_value_range_id, ask_for_match_interval, ask_for_numeric_range) VALUES
	(6, 'CBR:OBJECT-PROXIMITY', 'Object Proximity', 100, 0, 0, 1, 0, 0);
INSERT INTO MB_CBR_ATTRIBUTE_TYPE (attribute_type_id, symbol, display_name, default_match_contribution, default_mismatch_penalty,
	default_absence_penalty, default_value_range_id, ask_for_match_interval, ask_for_numeric_range) VALUES
	(7, 'CBR:RANGE', 'Numeric Range', 100, 0, 0, 4, 1, 1);
	
	
	
CREATE TABLE MB_DATE_SYNONYM (
	synonym_id   INT NOT NULL,
	synonym_name VARCHAR(255) NOT NULL,
	synonym_desc VARCHAR(255) NULL ,
	synonym_date DATETIME NOT NULL,
	is_named     BIT NULL ,
	PRIMARY KEY (synonym_id)
);

CREATE TABLE MB_GRID_DATE_SYNONYM (
	grid_id               INT NOT NULL ,
	effective_synonym_id  INT NOT NULL,
	expiration_synonym_id INT NOT NULL,
	PRIMARY KEY (grid_id)
);

INSERT INTO MB_PRIVILEGE (PRIVILEGE_ID,PRIVILEGE_NAME,DISPLAY_STRING) VALUES (42,'ManageDateSynonym','Manage Date Synonyms');
INSERT INTO MB_ROLE_PRIVILEGE (PRIVILEGE_ID,ROLE_ID) VALUES (42,2);



CREATE TABLE MB_TEMPLATE_VERSION (
    template_id  INT NOT NULL,
    version      VARCHAR(255) NOT NULL,
    PRIMARY KEY (template_id)
);

CREATE TABLE MB_CBR_CASE_BASE_DATE_SYNONYM (
	case_base_id          INT NOT NULL,
	effective_synonym_id  INT NOT NULL,
	expiration_synonym_id INT NOT NULL,
	PRIMARY KEY (case_base_id)
);

CREATE TABLE MB_CBR_CASE_DATE_SYNONYM (
	case_id               INT NOT NULL,
	effective_synonym_id  INT NOT NULL,
	expiration_synonym_id INT NOT NULL,
	PRIMARY KEY (case_id)
);

CREATE TABLE MB_PARAMETER_DATE_SYNONYM (
	parameter_id          INT NOT NULL ,
	effective_synonym_id  INT NOT NULL,
	expiration_synonym_id INT NOT NULL,
	PRIMARY KEY (parameter_id)
);


DROP TABLE MB_TEMPLATE_ALT_DEPLOY_USAGE;

CREATE TABLE MB_GUIDELINE_TEST_CONDITION (
    test_id				INT NOT NULL,
    test_name			VARCHAR(128) NOT NULL,
    test_desc		    VARCHAR(255),
    deployment_rule		MEMO NOT NULL,
    PRIMARY KEY (test_id)
);

INSERT INTO MB_PRIVILEGE (PRIVILEGE_ID,PRIVILEGE_NAME,DISPLAY_STRING) VALUES (8,'EditCategoryData','Edit Category Data');
INSERT INTO MB_ROLE_PRIVILEGE (PRIVILEGE_ID,ROLE_ID) VALUES (8,2);

INSERT INTO MB_PRIVILEGE (PRIVILEGE_ID,PRIVILEGE_NAME,DISPLAY_STRING) VALUES (33,'Print','Print');
INSERT INTO MB_ROLE_PRIVILEGE (PRIVILEGE_ID,ROLE_ID) VALUES (33,2);
INSERT INTO MB_ROLE_PRIVILEGE (PRIVILEGE_ID,ROLE_ID) VALUES (33,0);

DELETE from MB_NAMED_FILTER where name='All Investors';
DELETE from MB_NAMED_FILTER where name='All Products';
