/* Generated By:JavaCC: Do not edit this line. DeploymentRuleParserConstants.java */
package com.mindbox.pe.server.parser.jtb.rule;

public interface DeploymentRuleParserConstants {

  int EOF = 0;
  int MULTI_LINE_COMMENT = 7;
  int IF = 9;
  int THEN = 10;
  int TRUE = 11;
  int FALSE = 12;
  int ANY = 13;
  int ALL = 14;
  int AT = 15;
  int LEAST = 16;
  int MOST = 17;
  int EXISTS = 18;
  int WITH = 19;
  int EXCLUDING = 20;
  int NULL = 21;
  int AND = 22;
  int OR = 23;
  int IN = 24;
  int NIN = 25;
  int BETWEEN = 26;
  int NOT = 27;
  int IS = 28;
  int CREATE_BEGIN = 29;
  int CREATE_END = 30;
  int MESSAGE = 31;
  int COLUMN = 32;
  int CELLVALUE = 33;
  int RULENAME = 34;
  int ROW_NUMBER = 35;
  int CATEGORY_ID = 36;
  int CATEGORY_NAME = 37;
  int CHANNEL_ID = 38;
  int INVESTOR_ID = 39;
  int PRODUCT_ID = 40;
  int LINEAGE_ID = 41;
  int ACT_DATE = 42;
  int EXP_DATE = 43;
  int INTEGER_LITERAL = 44;
  int DECIMAL_LITERAL = 45;
  int HEX_LITERAL = 46;
  int OCTAL_LITERAL = 47;
  int FLOATING_POINT_LITERAL = 48;
  int EXPONENT = 49;
  int CHARACTER_LITERAL = 50;
  int STRING_LITERAL = 51;
  int IDENTIFIER = 52;
  int LETTER = 53;
  int DIGIT = 54;
  int HYPHEN = 55;
  int COLON = 56;
  int LPAREN = 57;
  int RPAREN = 58;
  int LBRACE = 59;
  int RBRACE = 60;
  int LBRACKET = 61;
  int RBRACKET = 62;
  int COMMA = 63;
  int DOT = 64;
  int AND_SYM = 65;
  int OR_SYM = 66;
  int BANG = 67;
  int GT = 68;
  int LT = 69;
  int EQ = 70;
  int LE = 71;
  int GE = 72;
  int NE = 73;
  int PLUS = 74;
  int MINUS = 75;
  int STAR = 76;
  int SLASH = 77;
  int PERCENT = 78;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"if\"",
    "\"then\"",
    "\"true\"",
    "\"false\"",
    "\"any\"",
    "\"all\"",
    "\"at\"",
    "\"least\"",
    "\"most\"",
    "\"exists\"",
    "\"with\"",
    "\"excluding\"",
    "\"null\"",
    "\"and\"",
    "\"or\"",
    "\"in\"",
    "\"notin\"",
    "\"between\"",
    "\"not\"",
    "\"is\"",
    "\"create$\"",
    "\"$create\"",
    "\"message\"",
    "\"column\"",
    "\"cellValue\"",
    "\"ruleName\"",
    "\"rowNumber\"",
    "\"categoryID\"",
    "\"categoryName\"",
    "\"channelID\"",
    "\"investorID\"",
    "\"productID\"",
    "\"lineageID\"",
    "\"activationDate\"",
    "\"expirationDate\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<HYPHEN>",
    "<COLON>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"|\"",
  };

}
