/* Generated By:JavaCC: Do not edit this line. MessageParserConstants.java */
package com.mindbox.pe.server.parser.jtb.message;

public interface MessageParserConstants {

  int EOF = 0;
  int COLUMN = 4;
  int COLUMN_SPACE = 5;
  int CELLVALUE = 6;
  int RULENAME = 7;
  int COLUMN_MESSAGES = 8;
  int INTEGER_LITERAL = 9;
  int DECIMAL_LITERAL = 10;
  int HEX_LITERAL = 11;
  int PERCENT = 12;
  int VBAR = 13;
  int PERIOD = 14;
  int LPARAN = 15;
  int RPARAN = 16;
  int COMMA = 17;
  int IDENTIFIER = 18;
  int LETTER = 19;
  int DIGIT = 20;
  int HYPHEN = 21;
  int COLON = 22;
  int VALID_FREE_CHAR = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"column\"",
    "\"column \"",
    "\"cellValue\"",
    "\"ruleName\"",
    "\"columnMessages\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "\"%\"",
    "\"|\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<HYPHEN>",
    "<COLON>",
    "<VALID_FREE_CHAR>",
    "\"%column\"",
    "\"%column \"",
    "\"%columnMessages\"",
  };

}
